pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('dockerhub-creds')
        ORACLE = credentials('oracle-db-creds')
        IMAGE_NAME = "amazon-rating-prediction"
        CONTAINER_NAME = "prediction-test-server"
        DB_CONTAINER_NAME = "oracle-test-db"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Container Locally') {
            steps {
                sh "docker rm -f $CONTAINER_NAME || true"
                sh "docker rm -f $DB_CONTAINER_NAME || true"
                
                sh "docker pull $DOCKERHUB_USR/$IMAGE_NAME:latest"
                sh "docker pull gvenzl/oracle-free:slim"

                script {
                    sh '''
                        JENKINS_ID=$(hostname)
                        docker inspect -f '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{end}}' $JENKINS_ID > network.txt
                    '''
                    def JENKINS_NET = readFile('network.txt').trim()
                    echo "Jenkins находится в сети: ${JENKINS_NET}"

                    sh """
                        docker run -d \
                        --name $DB_CONTAINER_NAME \
                        --network ${JENKINS_NET} \
                        -e ORACLE_PASSWORD=${ORACLE_PSW} \
                        -e APP_USER=${ORACLE_USR} \
                        -e APP_PASSWORD=${ORACLE_PSW} \
                        gvenzl/oracle-free:slim
                    """

                    echo "Waiting for Oracle DB to be healthy..."
                    sh '''
                        for i in {1..30}; do
                            HEALTH_STATUS=$(docker inspect --format="{{json .State.Health.Status}}" oracle-test-db)
                            if [ "$HEALTH_STATUS" == '"healthy"' ]; then
                                echo "Oracle DB is ready!"
                                break
                            fi
                            echo "Waiting... ($i/30)"
                            sleep 5
                        done
                    '''

                    sh """
                        docker run -d \
                        --name $CONTAINER_NAME \
                        --network ${JENKINS_NET} \
                        -e DB_USER=${ORACLE_USR} \
                        -e DB_PASSWORD=${ORACLE_PSW} \
                        -e DB_HOST=$DB_CONTAINER_NAME \
                        -e DB_PORT=1521 \
                        -e DB_SERVICE=FREEPDB1 \
                        $DOCKERHUB_USR/$IMAGE_NAME:latest
                    """
                    
                }
                
                sleep 5 
            }
        }

        stage('Run Scenario Tests') {
            steps {
                script {
                    def CONTAINER_IP = sh(script: "docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_NAME", returnStdout: true).trim()
                    echo "API Container IP is: ${CONTAINER_IP}"
                    
                    withEnv(["API_URL=http://${CONTAINER_IP}:8000"]) {
                        sh '''
                            python3 -m venv venv-cd
                            
                            . venv-cd/bin/activate
                            
                            pip install requests
                            
                            python3 tests/run_scenario.py
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo "CD pipline tests successfully done!"
        }
        failure {
            echo "Tests failed!"
            sh "docker logs $CONTAINER_NAME || true"
            sh "docker logs $DB_CONTAINER_NAME || true"
        }
        cleanup {
            sh "docker rm -f $CONTAINER_NAME || true"
            sh "docker rm -f $DB_CONTAINER_NAME || true"
            sh "docker logout || true"
        }
    }
}